# 2.2 Negation As Failure

SELECT ?timestamp ?maneuver
WHERE {

    ?vehicleState a :VehicleState ;
        :hasTimeStamp ?timestamp ;
        :canSafely ?maneuver .

} ORDER BY ASC(?timestamp) LIMIT 10
