SELECT ?device ?atLeastOneDependencyOn ?noDependenciesOff
WHERE {
    ?device a :Component .
    OPTIONAL {SELECT ?device ?atLeastOneDependencyOn
              WHERE {
                  ?device :atLeastOneDependencyOn ?atLeastOneDependencyOn .
              }
    }
    OPTIONAL {SELECT ?device ?noDependenciesOff
              WHERE {
                  ?device :noDependenciesOff ?noDependenciesOff .
              }
    }
} ORDER BY ASC(?device)