SELECT ?bathReadingEncoded ?time ?temperatureEstimate 
WHERE {
    ?bathReadingEncoded a :BathSummary ;
        :hasTimeStamp ?time ;
        :hasTemperatureEstimate ?temperatureEstimate .
} ORDER BY ASC(?time)