# 3.4 Transitive Closure

SELECT ?cyclicAsset ?downstreamAsset
WHERE {
    ?cyclicAsset a :CyclicAsset ;
        :dependsOn ?downstreamAsset .
    
    ?downstreamAsset a :CyclicAsset .
} ORDER BY ASC(?cyclicAsset)
